services:
  db:
    image: postgres:18.0
    volumes:
      - db:/var/lib/postgresql/18/docker
      - ./database/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bochitabi
    ports:
      - "5432:5432"

  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - 8080:8080

volumes:
  db:
