CREATE ROLE app WITH LOGIN;
ALTER ROLE app WITH PASSWORD 'password';
GRANT ALL PRIVILEGES ON SCHEMA bochitabi TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA bochitabi GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;