// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePicture = "pictures"

// Picture mapped from table <pictures>
type Picture struct {
	ID       string `gorm:"column:id;not null;default:uuidv7()" json:"id"`
	MemoryID string `gorm:"column:memory_id" json:"memory_id"`
	URL      string `gorm:"column:url" json:"url"`
}

// TableName Picture's table name
func (*Picture) TableName() string {
	return TableNamePicture
}
