name: Backend Pipeline
on: workflow_dispatch
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  REGION: ${{ secrets.GCP_REGION }}
  REGISTRY: ${{ secrets.REGISTRY }}
  REPOSITORY: ${{ secrets.REPOSITORY }}
  APP_NAME: bochitabi
jobs:
  backend-build:
    name: backend build
    runs-on: ubuntu-latest
    steps:
      - name: Source checkout
        uses: actions/checkout@v5

      - name: Authentication
        uses: google-github-actions/auth@v3  
        with:
          workload_identity_provider: $WORKLOAD_IDENTITY_PROVIDER
          service_account: $SERVICE_ACCOUNT
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build Docker image
        run: -|
          cd Backend
          docker build -t $REGISTRY/$PROJECT_ID/$REPOSITORY/$APP_NAME/:$GITHUB_SHA . 
          docker tag $REGISTRY/$PROJECT_ID/$REPOSITORY/$APP_NAME/:$GITHUB_SHA $REGISTRY/$PROJECT_ID/$REPOSITORY/$APP_NAME/:latest
      
      - name: Push Docker image
        run: -|
          docker push $REGISTRY/$PROJECT_ID/$REPOSITORY/$APP_NAME/:$GITHUB_SHA
          docker push $REGISTRY/$PROJECT_ID/$REPOSITORY/$APP_NAME/:latest
      