name: Backend Pipeline
on: workflow_dispatch
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  REGISTRY: ${{ secrets.GCP_REGISTRY }}
  REPOSITORY: ${{ secrets.GCP_REPOSITORY }}
  APP_NAME: bochitabi
jobs:
  backend-build:
    name: backend build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Source checkout
        uses: actions/checkout@v5

      - name: Authentication
        uses: google-github-actions/auth@v3  
        with:
          project_id: $PROJECT_ID
          workload_identity_provider: projects/$PROJECT_NUMBER/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions
          service_account: $SERVICE_ACCOUNT
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGISTRY

      - name: Build Docker image
        run: -|
          cd Backend
          docker build -t $REGISTRY/$PROJECT_ID/$REPOSITORY/$APP_NAME/:$GITHUB_SHA . 
          docker tag $REGISTRY/$PROJECT_ID/$REPOSITORY/$APP_NAME/:$GITHUB_SHA $REGISTRY/$PROJECT_ID/$REPOSITORY/$APP_NAME/:latest
      
      - name: Push Docker image
        run: -|
          docker push $REGISTRY/$PROJECT_ID/$REPOSITORY/$APP_NAME/:$GITHUB_SHA
          docker push $REGISTRY/$PROJECT_ID/$REPOSITORY/$APP_NAME/:latest